# Generated by Django 3.0.4 on 2020-04-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='开课日期')),
                ('end_date', models.DateField(verbose_name='结课日期')),
                ('short_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='简介')),
                ('offering_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plan.OfferingCourse', verbose_name='开设课程')),
            ],
            options={
                'verbose_name': '历史课程',
                'verbose_name_plural': '历史课程',
            },
        ),
    ]
