# Generated by Django 3.0.4 on 2020-04-23 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200423_1504'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatormark',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_marks', to='course.Grade', verbose_name='成绩和评价'),
        ),
        migrations.AlterField(
            model_name='indicatormark',
            name='indicator_factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_marks', to='plan.IndicatorFactor', verbose_name='支撑课程以及指标系数'),
        ),
    ]
