# Generated by Django 3.0.4 on 2020-04-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediction', '0001_initial'),
        ('user', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cms',
            field=models.ManyToManyField(to='user.CM', verbose_name='课程负责人'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(through='prediction.Grade', to='user.Student', verbose_name='参与学生'),
        ),
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(to='user.Teacher', verbose_name='负责教师'),
        ),
    ]
