# Generated by Django 3.0.4 on 2020-04-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200423_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='cm',
        ),
        migrations.AddField(
            model_name='course',
            name='review_status',
            field=models.CharField(choices=[('未通过', '未通过'), ('未审核', '未审核'), ('已审核', '已审核')], default='未审核', max_length=10, verbose_name='审核状态'),
        ),
    ]
