# Generated by Django 3.0.4 on 2020-04-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0002_auto_20200421_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_marks', models.FloatField(blank=True, null=True, verbose_name='结课分数')),
                ('indicator', models.FloatField(blank=True, null=True, verbose_name='评价分数')),
                ('cm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.CM', verbose_name='审核人')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='course.Course', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩和评价',
                'verbose_name_plural': '成绩和评价',
            },
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='unique_grade'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('course', 'student')},
        ),
    ]
