# Generated by Django 3.0.4 on 2020-04-24 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('course', '0003_auto_20200423_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='review_comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='审核人评论'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', through='course.Grade', to='user.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cms',
            field=models.ManyToManyField(related_name='courses', to='user.CM', verbose_name='课程负责人'),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', to='user.Teacher', verbose_name='负责教师'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='course.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='user.Student', verbose_name='学生'),
        ),
    ]
