# Generated by Django 3.0.4 on 2020-04-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roughrequirement',
            name='index',
            field=models.IntegerField(default=1, verbose_name='序号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roughrequirement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
