# Generated by Django 3.0.4 on 2020-04-23 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailedrequirement',
            name='full_indicator',
        ),
        migrations.RemoveField(
            model_name='roughrequirement',
            name='full_indicator',
        ),
        migrations.RemoveField(
            model_name='roughrequirement',
            name='indicator_warning_line',
        ),
    ]
