# Generated by Django 3.0.4 on 2020-04-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200422_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roughrequirement',
            name='index',
            field=models.IntegerField(unique=True, verbose_name='序号'),
        ),
    ]
