# Generated by Django 3.0.4 on 2020-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20200423_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicatorfactor',
            name='target',
            field=models.TextField(blank=True, null=True, verbose_name='课程教学目标'),
        ),
    ]
