# Generated by Django 3.0.4 on 2020-04-22 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20200422_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedrequirement',
            name='rough_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detailed_requirements', to='plan.RoughRequirement', verbose_name='毕业要求'),
        ),
        migrations.AlterField(
            model_name='indicatorfactor',
            name='detailed_requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_factors', to='plan.DetailedRequirement', verbose_name='指标点'),
        ),
        migrations.AlterField(
            model_name='indicatorfactor',
            name='offering_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_factors', to='plan.OfferingCourse', verbose_name='课程'),
        ),
    ]
