# Generated by Django 3.0.4 on 2020-04-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20200423_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roughrequirement',
            name='index',
            field=models.IntegerField(verbose_name='序号'),
        ),
    ]
