# Generated by Django 3.0.4 on 2020-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20200423_0229'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='detailedrequirement',
            name='unique_detailed_requirement',
        ),
        migrations.AlterUniqueTogether(
            name='detailedrequirement',
            unique_together=set(),
        ),
    ]
