# Generated by Django 3.0.4 on 2020-04-24 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CM',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='账户')),
            ],
            options={
                'verbose_name': '课程负责人',
                'verbose_name_plural': '课程负责人',
            },
        ),
        migrations.CreateModel(
            name='PM',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='账户')),
            ],
            options={
                'verbose_name': '专业负责人',
                'verbose_name_plural': '专业负责人',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='班级名')),
                ('created_year', models.IntegerField(verbose_name='年级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='账户')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='账户')),
            ],
            options={
                'verbose_name': '导员',
                'verbose_name_plural': '导员',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='账户')),
                ('admission_date', models.DateField(verbose_name='入学日期')),
                ('graduation_date', models.DateField(verbose_name='毕业日期')),
                ('length_of_schooling', models.IntegerField(default=4, verbose_name='学制')),
                ('field_of_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='plan.FieldOfStudy', verbose_name='专业方向')),
                ('squad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Squad', verbose_name='班级')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.AddField(
            model_name='squad',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Tutor', verbose_name='导员'),
        ),
    ]
